name: Semgrep Scan

on:
  workflow_call:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Checkout Semgrep rules
        uses: actions/checkout@v5
        with:
          repository: dgryski/semgrep-go
          path: rules

      - name: Run Semgrep scan
        run: semgrep scan --error --enable-nosem -f ./rules .
